# Generated by Django 3.2.7 on 2021-10-04 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_network", "0003_auto_20210929_0926"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="post_authors_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="PostAuthorLike",
        ),
    ]
